# -*- coding: utf-8 -*-
"""TCS PROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kt-uiNULJxD-0gCQopJ4qJioE82-B_AQ
"""

!pip install easyocr

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] = 8, 16

reader = easyocr.Reader(['en'])

Image("Image1.jpg")

output = reader.readtext('Image1.jpg')

output

cord = output[-1][0]

x_min, y_min = [min(idx) for idx in zip(*cord)]

x_max, y_max = [max(idx) for idx in zip(*cord)]

image = cv2.imread('Image1.jpg')
cv2.rectangle(image, (x_min, y_min), (x_max, y_max), (0, 0, 255), 2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))